services:
  fastapi:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
#    restart: always
    volumes:
      - ../src:/home/app/web/src
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    healthcheck:
      test: curl --fail -s http://0.0.0.0:8080 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=roflateliedbuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=authservicepostgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:6.2-alpine
    ports:
        - 6379:6379
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=redis
      - REDIS_PASSWORD=password
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
        - cache:/data

volumes:
  postgres_data:
  cache:
